version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ramondpaula/nest
    container_name: node-nest
    tty: true
    command: npm run start
    restart: always
    volumes:
     - .:/app
    networks:
     - net-nest
    ports:
      - "8000:8000"


networks:
  net-nest:
    driver: bridge
